[CI] Avoid git clone issue on self hosted runners (#2259)
Self-hosted runners were hitting exit 128 ("could not read Username
for 'https://github.com/'") on plain git clones done outside
actions/checkout (AdaptiveCpp source build, reference-files pull, ...)

Exact error message:

-> git clone -b v25.02.0 https://github.com/AdaptiveCpp/AdaptiveCpp.git /__w/Shamrock/Shamrock/build/.env/acpp-git
Cloning into '/__w/Shamrock/Shamrock/build/.env/acpp-git'...
fatal: could not read Username for 'https://github.com': No such device or address
fatal: expected flush after ref listing
Error: Process completed with exit code 128.

The fix applied here is to force the use of a GitHub token to clone even when using http. I think that the IP is borderline blacklisted when using git clone (http request still work though) from self hosted. So we use a token to avoid that issue.