[Backends] use c++20 to improve error messages (#1814)
dramatically simplify the error message for wrong signature in a kernel call lambda from 365 lines to 19 !

The current error message now look like:
```
error: static assertion failed due to requirement 
'matches_expected_kernel_signature<void (unsigned int, const double *, const double *, double *, double *)>': 
Kernel functor is not invocable with the expected signature; see matches_expected_kernel_signature<void(...)> 
for the required argument list.
```

Approved-by: shamrock-code-admin <312975147+shamrock-code-admin@users.noreply.github.com>
Merged-by: Mergify <37929162+mergify[bot]@users.noreply.github.com>